### PR TITLE
Updated examples

### PR DESCRIPTION
**Pull request by sharkbait-au**

### CODE REVIEW

**Comment by LJWall** [comment]
Hi Sharkbait,  I don't think `layout.ejs` is being used properly now?  It gives the login/log-out links without needing to modify `index.ejs`.   I used `express-ejs-layouts instead` of `ejs` as a requirement and 
```javascript
app.use(require('express-ejs-layouts'));
```

**Comment by sharkbait-au** [comment]
I'm sure your probably right. I'm a newb. I only changed the bare minimum to get the sample working for me + added the login link because I didn't want to have to type in an address. I never even looked at the layout file, and I never saw a working example to know it should have been there.

**Comment by sharkbait-au** [comment]
Thanks LJWall. Finally got around to implementing your solution.

**Comment by metaraine** [comment]
Please accept this pull request. Would have saved me a lot of time.

**Comment by danrpts** [comment]
:+1:

**Comment by jaredhanson** [comment]
Examples are moving to separate repositories. Closing.

**Pull request closed without merging**
